# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/bkd/git/kdJavaLogViewer/kdJavaLogViewer\kdJavaLogViewer.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.te_start = QtWidgets.QTimeEdit(self.groupBox)
        self.te_start.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.te_start.setCalendarPopup(True)
        self.te_start.setTime(QtCore.QTime(0, 0, 0))
        self.te_start.setObjectName("te_start")
        self.gridLayout.addWidget(self.te_start, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 4, 1, 1)
        self.te_end = QtWidgets.QTimeEdit(self.groupBox)
        self.te_end.setCalendarPopup(True)
        self.te_end.setObjectName("te_end")
        self.gridLayout.addWidget(self.te_end, 2, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.le_prefex = QtWidgets.QLineEdit(self.groupBox)
        self.le_prefex.setObjectName("le_prefex")
        self.gridLayout.addWidget(self.le_prefex, 3, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 4, 1, 1)
        self.le_thread = QtWidgets.QLineEdit(self.groupBox)
        self.le_thread.setText("")
        self.le_thread.setObjectName("le_thread")
        self.gridLayout.addWidget(self.le_thread, 3, 5, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 1, 1, 1)
        self.cb_debug = QtWidgets.QCheckBox(self.groupBox)
        self.cb_debug.setObjectName("cb_debug")
        self.gridLayout.addWidget(self.cb_debug, 4, 2, 1, 1)
        self.cb_info = QtWidgets.QCheckBox(self.groupBox)
        self.cb_info.setObjectName("cb_info")
        self.gridLayout.addWidget(self.cb_info, 4, 3, 1, 1)
        self.cb_warn = QtWidgets.QCheckBox(self.groupBox)
        self.cb_warn.setObjectName("cb_warn")
        self.gridLayout.addWidget(self.cb_warn, 4, 5, 1, 1)
        self.cb_error = QtWidgets.QCheckBox(self.groupBox)
        self.cb_error.setObjectName("cb_error")
        self.gridLayout.addWidget(self.cb_error, 4, 6, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 1, 1, 1)
        self.le_method = QtWidgets.QLineEdit(self.groupBox)
        self.le_method.setObjectName("le_method")
        self.gridLayout.addWidget(self.le_method, 5, 2, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 4, 1, 1)
        self.le_keyword = QtWidgets.QLineEdit(self.groupBox)
        self.le_keyword.setObjectName("le_keyword")
        self.gridLayout.addWidget(self.le_keyword, 5, 5, 1, 2)
        self.pb_open = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_open.sizePolicy().hasHeightForWidth())
        self.pb_open.setSizePolicy(sizePolicy)
        self.pb_open.setObjectName("pb_open")
        self.gridLayout.addWidget(self.pb_open, 0, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.pb_query = QtWidgets.QPushButton(self.groupBox)
        self.pb_query.setObjectName("pb_query")
        self.gridLayout.addWidget(self.pb_query, 0, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.le_encoding = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_encoding.sizePolicy().hasHeightForWidth())
        self.le_encoding.setSizePolicy(sizePolicy)
        self.le_encoding.setObjectName("le_encoding")
        self.gridLayout.addWidget(self.le_encoding, 0, 5, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tb_result = QtWidgets.QTextBrowser(self.groupBox_2)
        self.tb_result.setObjectName("tb_result")
        self.verticalLayout_2.addWidget(self.tb_result)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Java日志查看器"))
        self.groupBox.setTitle(_translate("MainWindow", "导入和查询"))
        self.te_start.setDisplayFormat(_translate("MainWindow", "HH:mm:ss"))
        self.label_2.setText(_translate("MainWindow", "结束时间"))
        self.te_end.setDisplayFormat(_translate("MainWindow", "HH:mm:ss"))
        self.label_5.setText(_translate("MainWindow", "线程号前缀"))
        self.le_prefex.setText(_translate("MainWindow", "T"))
        self.label_3.setText(_translate("MainWindow", "线程号"))
        self.label_6.setText(_translate("MainWindow", "日志级别"))
        self.cb_debug.setText(_translate("MainWindow", "debug"))
        self.cb_info.setText(_translate("MainWindow", "info"))
        self.cb_warn.setText(_translate("MainWindow", "warn"))
        self.cb_error.setText(_translate("MainWindow", "error"))
        self.label_7.setText(_translate("MainWindow", "方法"))
        self.label_8.setText(_translate("MainWindow", "关键字"))
        self.pb_open.setText(_translate("MainWindow", "打开日志文件"))
        self.label.setText(_translate("MainWindow", "开始时间"))
        self.pb_query.setText(_translate("MainWindow", "查询"))
        self.label_4.setText(_translate("MainWindow", "编码格式"))
        self.groupBox_2.setTitle(_translate("MainWindow", "结果"))

