# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/bkd/git/kdJavaLogViewer\kdJavaLogViewer\kdJavaLogViewer.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_import = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_import.sizePolicy().hasHeightForWidth())
        self.pb_import.setSizePolicy(sizePolicy)
        self.pb_import.setObjectName("pb_import")
        self.gridLayout.addWidget(self.pb_import, 0, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.te_start = QtWidgets.QTimeEdit(self.groupBox)
        self.te_start.setObjectName("te_start")
        self.gridLayout.addWidget(self.te_start, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        self.te_end = QtWidgets.QTimeEdit(self.groupBox)
        self.te_end.setObjectName("te_end")
        self.gridLayout.addWidget(self.te_end, 1, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.le_prefex = QtWidgets.QLineEdit(self.groupBox)
        self.le_prefex.setObjectName("le_prefex")
        self.gridLayout.addWidget(self.le_prefex, 2, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 3, 1, 1)
        self.le_thread = QtWidgets.QLineEdit(self.groupBox)
        self.le_thread.setObjectName("le_thread")
        self.gridLayout.addWidget(self.le_thread, 2, 4, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.cb_debug = QtWidgets.QCheckBox(self.groupBox)
        self.cb_debug.setObjectName("cb_debug")
        self.gridLayout.addWidget(self.cb_debug, 3, 1, 1, 1)
        self.cb_info = QtWidgets.QCheckBox(self.groupBox)
        self.cb_info.setObjectName("cb_info")
        self.gridLayout.addWidget(self.cb_info, 3, 2, 1, 1)
        self.cb_warn = QtWidgets.QCheckBox(self.groupBox)
        self.cb_warn.setObjectName("cb_warn")
        self.gridLayout.addWidget(self.cb_warn, 3, 4, 1, 1)
        self.cb_error = QtWidgets.QCheckBox(self.groupBox)
        self.cb_error.setObjectName("cb_error")
        self.gridLayout.addWidget(self.cb_error, 3, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.le_class = QtWidgets.QLineEdit(self.groupBox)
        self.le_class.setObjectName("le_class")
        self.gridLayout.addWidget(self.le_class, 4, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 3, 1, 1)
        self.le_keyword = QtWidgets.QLineEdit(self.groupBox)
        self.le_keyword.setObjectName("le_keyword")
        self.gridLayout.addWidget(self.le_keyword, 4, 4, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tb_result = QtWidgets.QTextBrowser(self.groupBox_2)
        self.tb_result.setObjectName("tb_result")
        self.verticalLayout_2.addWidget(self.tb_result)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "导入和查询"))
        self.pb_import.setText(_translate("MainWindow", "导入日志文件"))
        self.label.setText(_translate("MainWindow", "开始时间"))
        self.label_2.setText(_translate("MainWindow", "结束时间"))
        self.label_5.setText(_translate("MainWindow", "线程号前缀"))
        self.le_prefex.setText(_translate("MainWindow", "T"))
        self.label_3.setText(_translate("MainWindow", "线程号"))
        self.label_6.setText(_translate("MainWindow", "日志级别"))
        self.cb_debug.setText(_translate("MainWindow", "debug"))
        self.cb_info.setText(_translate("MainWindow", "info"))
        self.cb_warn.setText(_translate("MainWindow", "warn"))
        self.cb_error.setText(_translate("MainWindow", "error"))
        self.label_7.setText(_translate("MainWindow", "类"))
        self.label_8.setText(_translate("MainWindow", "关键字"))
        self.groupBox_2.setTitle(_translate("MainWindow", "结果"))

